# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iSask1B6CaasmUtsCYinR-YFzSq-Zct5
"""

import matplotlib.pyplot as plt
#import numpy as np
#import pandas as pd

#expenses={'Rent':200}
expense=[1200,200, 300, 150, 100, 50]
items=["Rent", "Utilities", "Groceries", "Transportstion", "Entertainment", "other"]
plt.pie(expense, labels=items, autopct="%.1f%%", startangle=90, explode=[0, 0, 0.2, 0, 0, 0])
plt.legend()
plt.show()

expense=[1200,200,300, 150, 100, 50]
items=["Rent", "Utilities", "Groceries", "Transportation", "Entertainment", "Other"]
plt.pie(expense, labels=items, autopct="%.1f%%", startangle=90, explode=[0, 0, 0.2, 0, 0, 0])
plt.legend()
plt.show()

"""1. Write code a pyhton code to create a pie chart for how many students got each grade in the recent test. Write down percentage also.

A   B   C   D
4   12  10  2

2. survey of 145 people asked them "Which is the nicest fruit?" Wite a pyhton code to create a bar graph


Fruit:
"""

fruit=["Apple", "Orange", "Banana", "Kiwi", "Blueberry", "Grapes"]
people=[12,5,7,9,4,10]
plt.bar(people, label=fruit)
plt.show()

"""how much is that puppy growing? Write pyhton code to create histogram
heihgt of the puppies.
0.5, 0.5, 0.3, -0.2, 1.6, 0, 0.1, 0.1, 0.6, 0.4
"""

a=[0.5, 0.5, 0.3, -0.2, 0.6, 0, 0.1, 0.1, 0.6, 0.4]
plt.hist(a, bins=[-0.3,-0.1,0.1,0.3,0.5,0.7])
plt.show()

studyhrs=[1,2,3,4,5,6,7,8,9,10]
exam_score=[55,60,65,70,75,80,85,90,95,100]
plt.scatter(studyhrs,exam_score)
plt.show()